{% set version = "0.1.5" %}

package:
  name: osmnet
  version: {{ version }}

source:
  url: https://github.com/UDST/osmnet/archive/v{{ version }}.tar.gz
  sha256: 335a69e4976930e18199a15f4b47cf5fa1b85b3c4aae7c5c0492a3f0b1fe66fb

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.9.1
    - pandas >=0.16.0
    - numpy >=1.10
    - geopandas >=0.2.1
    - shapely >=1.5

test:
  imports:
    - osmnet

about:
  home: https://github.com/UDST/osmnet
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: 'Tools for the extraction of OpenStreetMap street network data for use in Pandana accessibility analyses.'
  description: |
    Tools for the extraction of OpenStreetMap (OSM) street network data.
    Intended to be used in tandem with Pandana and UrbanAccess libraries to
    extract street network nodes and edges.
  doc_url: https://udst.github.io/osmnet/
  dev_url: https://github.com/UDST/osmnet

extra:
  recipe-maintainers:
    - pksohn
