{% set name = "osmnet" %}
{% set version = "0.1.5" %}
{% set sha256 = "2fb96a7a95e34af45d1b8c5f88705da6876143820781220b1f55adf1f242639e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.9.1
    - pandas >=0.16.0
    - numpy >=1.10
    - geopandas >=0.2.1
    - shapely >=1.5

test:
  imports:
    - osmnet

about:
  home: https://github.com/UDST/osmnet
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: 'Tools for the extraction of OpenStreetMap street network data for use in Pandana accessibility analyses.'
  description: |
    Tools for the extraction of OpenStreetMap (OSM) street network data.
    Intended to be used in tandem with Pandana and UrbanAccess libraries to
    extract street network nodes and edges.
  doc_url: https://udst.github.io/osmnet/
  dev_url: https://github.com/UDST/osmnet

extra:
  recipe-maintainers:
    - smmaurer
