{% set version = "0.1.6" %}

package:
  name: osmnet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/osmnet/osmnet-{{ version }}.tar.gz
  sha256: 3cfb73317e59286797913e68ea3134205786ff1221111bbc5044b76ed8d26335

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=2.9.1
    - pandas >=0.16.0
    - numpy >=1.10
    - geopandas >=0.2.1
    - shapely >=1.5

test:
  imports:
    - osmnet

about:
  home: https://github.com/UDST/osmnet
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: Tools for the extraction of OpenStreetMap street network data for use in Pandana accessibility analyses.
  description: |
    Tools for the extraction of OpenStreetMap (OSM) street network data.
    Intended to be used in tandem with Pandana and UrbanAccess libraries to
    extract street network nodes and edges.
  doc_url: https://udst.github.io/osmnet/
  dev_url: https://github.com/UDST/osmnet

extra:
  recipe-maintainers:
    - pksohn
    - smmaurer
