{% set name = "osmnet" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UDST/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1e6234a82ff6a672d0aeb3d8b7b684905808bfbf9087876d1b8d3d897c127c80

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - requests >=2.9.1
    - pandas >=0.16.0
    - numpy >=1.10
    - geopandas >=0.2.1
    - shapely >=1.5

test:
  imports:
    - osmnet

about:
  home: https://github.com/UDST/osmnet
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: 'Tools for the extraction of OpenStreetMap street network data for use in Pandana accessibility analyses.'
  description: |
    Tools for the extraction of OpenStreetMap (OSM) street network data.
    Intended to be used in tandem with Pandana and UrbanAccess libraries to
    extract street network nodes and edges.
  doc_url: https://udst.github.io/osmnet/
  dev_url: https://github.com/UDST/osmnet

extra:
  recipe-maintainers:
    - pksohn
