travis:
  secure:
    BINSTAR_TOKEN: PWL0RkPG0VzDBsMkk1pwT5b2XSeMUnheA7yGyUgbbQS6wZVqHz1sF6grVpq6mmP1YnJjry+9GVOvhFzp4vW13rkZ/FwZ2czqXG3Nvg9FwffpVwO4LnQtrGdYiIGbQ1qmVuI7x6+BFvUJgvx9GXVtc2JK7C5VG6gyFn1tDz0wYqNWOaFMHFy5M9WXJOj/VBT3QPEjyLEVbk6r3flKpVjYuKWi9umnJaXyiHMXByE2TSgHSRmP1MhokXoxxc5BYf//4EpJd+5hdRju2geOD4xzKbRrF+WQR4GySQXQ3FDFvtbPpIc/yIQZ9Ac352q/8VWQCcBqcXWEhiRKPEqKy5ntCdNPHJCZ/ky3id0/eDUFdNS3F+LmQ3MBQRl+oTzZT7V5PtRRxhgKt83rbXIbnXuF/sQZR5NBIGoiWEoX4bu2JJUS7FjmEUFCZfFFHvs93pxaa3BK8jWBHI6+/Zud4fGATs/WqML3iA/EpH5Ssps0T6Pb/awtTEL6YNWWX067ea6sAj9vSCWeDpudyXtIxBULm4cNWQHERgzc1woMdIeWCVk591hQh3tvyk+JShkAply3uPXa8As0cY+h9vZltqBF5G1PbYCXjB9A2bADwK9xXn6B6xxHg9PwWTfNpV5Xyepm+cCPlw21/ahcjb0sIOgcA/33gup0G5oh5QfiiiqKXzg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
