travis:
  secure:
    BINSTAR_TOKEN: OVk8oKnQQ+Qn1oaV9cRLd3+WDLcn+fGaW0mlM6aW7QeAimuvMDPuGy8+0lvnjFUR0YT8ga3ZZyKPvE3kUtWBH1lCiiI2ZmCMQLE5xKHbe7wpsOfvO91C5aKq/rBvPlzP17Wc+EKA0dxylBQhW2qeC4qS8tkfjHCyOIXHvcG4kPJ8+LBMhTtGc7iq+yhJ6LARjqJRctrN8VBFDoUwtKDqLFhNxC44uzIIz72XWyticddd5vQO4YG4qsRkOpA3ivl7v7ElZzps35gHsg21R1lnfsESDElpbKMxYlQl5VZVt95ujpTSjM4sxCU3YT1xdyMcb41nswI9Y9bSAevBNOTFaP79BQ2S8pvGOKYD4jaPuhEyl2LixRAP0fxhsdRe8izISPUl5KtXPB0JlfBNSFqEW/HozjZjJEg+85bu5Nbl43EJN9qBqZJ1hgcr9RxohWp5tskmTE5I++qQ09AamSIn5hsUinmwME6v5kDOjqCS+mpA+B/sDM5wB/uvqAA2EoY8FdwDvrCEVPYZ1OWwMq5hRZitbIR2QJB6tSvQ24Om///C7erjtc8/E2q/LK1t0XOc9y+l68LS82zw9fFCTCSMf8joTLiTmTHYfV68H2ijcwGa8VvYwdEzglMmJaQTwfkl8ZIsvsop89OS9vl0Gr2lfPS1vyx3TH+IqwdrS4QxyRU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
